export const regionsSeed = [
  {
    name: 'Kashmir', slug: 'kashmir', state: 'Jammu & Kashmir', craft: 'Pashmina',
    material: 'Changthangi goat wool',
    mapCoords: { lat: 34.0837, lng: 74.7973 },
    shortIntro: 'Handwoven at 12,000 feet, kept soft by the winters.',
    longStory: 'From the high plateaus of Changthang, the fine undercoat of the Changra goat is combed by nomadic herders, then spun and woven on traditional looms in Srinagar. Each shawl takes weeks; some take seasons.',
    order: 1,
  },
  {
    name: 'Kutch', slug: 'kutch', state: 'Gujarat', craft: 'Ajrakh block printing',
    material: 'Cotton, natural indigo, madder, myrobalan',
    mapCoords: { lat: 23.7337, lng: 69.8597 },
    shortIntro: 'Sixteen steps, twenty days, one uninterrupted lineage.',
    longStory: 'The Khatris of Ajrakhpur continue a 400-year-old resist-dyeing tradition. Every stage — from myrobalan soak to final wash — is done by hand, by families who have carried the craft across generations.',
    order: 2,
  },
  {
    name: 'Coorg', slug: 'coorg', state: 'Karnataka', craft: 'Shade-grown coffee',
    material: 'Arabica & Robusta under forest canopy',
    mapCoords: { lat: 12.3375, lng: 75.8069 },
    shortIntro: 'Grown under native trees, picked by hand, cup by cup.',
    longStory: 'On small estates in the Western Ghats, coffee grows slowly under rosewood and silver oak. We source from families who still pulp, ferment and sun-dry on the farm.',
    order: 3,
  },
  {
    name: 'Darjeeling', slug: 'darjeeling', state: 'West Bengal', craft: 'First-flush tea',
    material: 'Camellia sinensis, single-estate',
    mapCoords: { lat: 27.036, lng: 88.2627 },
    shortIntro: 'A terroir you can taste — muscatel, mist, and quiet.',
    longStory: 'Only a few hundred gardens in the hills earn the Darjeeling GI. Our leaves come from single-estate lots, harvested in March and April when the bushes first wake.',
    order: 4,
  },
  {
    name: 'Varanasi', slug: 'varanasi', state: 'Uttar Pradesh', craft: 'Banarasi silk',
    material: 'Katan silk, zari',
    mapCoords: { lat: 25.3176, lng: 82.9739 },
    shortIntro: 'Looms that have sung by the river for six centuries.',
    longStory: 'Along the lanes of Madanpura and Alaipur, weavers translate Mughal motifs into silk and zari — a craft passed father to son, loom by loom.',
    order: 5,
  },
  {
    name: 'Channapatna', slug: 'channapatna', state: 'Karnataka', craft: 'Lacquer-turned wood',
    material: 'Hale wood, natural lac, vegetable dyes',
    mapCoords: { lat: 12.6512, lng: 77.207 },
    shortIntro: 'Toy town — two centuries of colour on the lathe.',
    longStory: 'A craft introduced during Tipu Sultan\'s court, Channapatna turnery is recognised by GI. Safe, non-toxic dyes and softwood make these objects both beautiful and usable.',
    order: 6,
  },
  {
    name: 'Bikaner', slug: 'bikaner', state: 'Rajasthan', craft: 'Usta meenakari & miniatures',
    material: 'Camel hide, gold leaf, pigments',
    mapCoords: { lat: 28.0229, lng: 73.3119 },
    shortIntro: 'Desert light, gold leaf, patient hands.',
    longStory: 'The Usta families of Bikaner gild camel-hide lamps and boxes with a technique reserved, historically, for royal commissions.',
    order: 7,
  },
  {
    name: 'Kannauj', slug: 'kannauj', state: 'Uttar Pradesh', craft: 'Ittar (attar) distillation',
    material: 'Rose, khus, mitti, jasmine',
    mapCoords: { lat: 27.0649, lng: 79.9146 },
    shortIntro: 'India\'s perfume capital — copper stills, sandalwood base.',
    longStory: 'Using the centuries-old deg-bhapka method, flowers are distilled over sandalwood. Mitti attar — the scent of the first monsoon rain — is a Kannauj signature.',
    order: 8,
  },
  {
    name: 'Nagaland', slug: 'nagaland', state: 'Nagaland', craft: 'Bamboo & naga loin-loom',
    material: 'Bamboo, cotton, natural dyes',
    mapCoords: { lat: 26.1584, lng: 94.5624 },
    shortIntro: 'Hill weaves, warm weight, quiet geometry.',
    longStory: 'Across Angami and Ao villages, women weave narrow strips on back-strap looms, later stitched into shawls. We work directly with weaver cooperatives.',
    order: 9,
  },
  {
    name: 'Pondicherry', slug: 'pondicherry', state: 'Puducherry', craft: 'Handmade paper & letterpress',
    material: 'Cotton rag, natural fibres',
    mapCoords: { lat: 11.9416, lng: 79.8083 },
    shortIntro: 'Paper with a grain, ink with a press.',
    longStory: 'Auroville\'s paper studios recycle rag and plant fibre into sheets with character; letterpress studios nearby print with deep bite and restraint.',
    order: 10,
  },
  {
    name: 'Bhagalpur', slug: 'bhagalpur', state: 'Bihar', craft: 'Tussar silk',
    material: 'Wild cocoon silk',
    mapCoords: { lat: 25.2425, lng: 86.9842 },
    shortIntro: 'A silk that keeps the forest\'s texture.',
    longStory: 'Unlike cultivated mulberry silk, tussar comes from forest-reared cocoons. The yarn retains a soft gold and an honest, slubby grain.',
    order: 11,
  },
  {
    name: 'Kerala', slug: 'kerala', state: 'Kerala', craft: 'Spice & coconut',
    material: 'Cardamom, pepper, clove, virgin coconut',
    mapCoords: { lat: 10.8505, lng: 76.2711 },
    shortIntro: 'Monsoon spice — the route the world once sailed for.',
    longStory: 'From small estates in Idukki and Wayanad, we source green cardamom and black pepper at peak harvest, cold-milling and bottling within weeks.',
    order: 12,
  },
];
